#+TITLE: RAM(Robot de Afecciones Múltiples)-Simulation
#+AUTHOR: Hanan Quispe
#+DATE: 2022
#+options: toc:nil

Este repositorio contiene los scripts para ejecutar el demo del navigation stack usando Turtlebot3 y ROS(Robot Operating System), además de ello también contiene una interfaz gráfica para el control del robot desde una red local.

* Dependencias 
** ROS
La versión de ros utilizada es ROS Melodic esta se puede instalar siguiendo las instrucciones del siguiente enlace [[http://wiki.ros.org/melodic/Installation/Ubuntu][ROS Melodic]].
** Create React App
Referirse a [[https://github.com/facebook/create-react-app][Create React App]] para instalar las dependencias correspondientes.

** Dependencias Adicionales
Estas se instalan usando 
#+begin_src bash
  bash install.sh
#+end_src
* Configuración de la Interfaz
La simulación se ejecuta en dos computadoras, en una de ellas se ejecuta ROS con la simulación de Turtlebot3 y en la segunda se ejecuta la interfaz de control. 
En la computadora que ejecute la interfaz de control es necesario modificar [[./robot-ram/src/scripts/Config.js]] de la siguiente manera.
#+begin_src javascript

  const Config ={
      ROSBRIDGE_SERVER_IP:// poner la ip de la computadora que ejecute la simulacion de turtlebot3 aqui,
      ROSBRIDGE_SERVER_PORT:"9090",
      TIME_RECONNECTION: 3000, //ms
      CMD_VEL_TOPIC:"/cmd_vel",
      POSE_TOPIC: "/amcl_pose",
      ODOM_TOPIC: "/odom",
      VEl_LIN_MAX: 0.5, // m/s 
      VEL_ANG_MAX: 0.5, // rad/s
  };

  export default Config;
#+end_src

Para conocer la dirección ip de la maquina que ejecute la simulación de Turtlebot3 usar ejecutar lo siguiente en un terminal.

#+begin_src bash
  ifconfig
#+end_src

* Ejecución del Simulador
** Inicialización de la Simulación de Turtlebot3
#+begin_src bash
  bash run_robot.sh
#+end_src
** Inicialización de la Interfaz de Control
#+begin_src bash
  bash run_gui.sh
#+end_src

